services:
  - type: web
    name: imageawareplus
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: VT_API_KEY
        sync: false
      - key: URLSCAN_API_KEY
        sync: false
      - key: PHISHTANK_API_KEY
        sync: false
